### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by bokey007** [robertanto/Real-Time-Sound-Event-Detection#1]
Hi, Thank you so much
for this wonderful Repository 

I was more interested to
train sound event detection on my own dataset 

can you please let
me know from where
did you take this
model or How you
trained it.

I would really appreciate any possible
help/guidance on this.

**Comment by robertanto** [comment]
Hi!

Thank you for being so interested! The name of the neural network is Yamnet. It is a MobileNet v2 trained on audioset.

You can refer to this article [https://arxiv.org/abs/1609.09430](link) for details.
