### ISSUE TITLE
improve temporal prediction

### ISSUE THREAD

**Issue by Xand04** [robertanto/Real-Time-Sound-Event-Detection#3]
Hello! Thank you very much for this very interesting project. I was wondering if it was possible to improve temporal precision of the prediction by decreasing the WIN_SIZE_SEC. However, I get a layer size error (for WIN_SIZE_SEC = 0.975/2).

![image](https://user-images.githubusercontent.com/45367529/235667499-3a63f429-1d4e-4ac7-af54-b52d8786fb4e.png)

This is of course depending on the size of the layers of your training model. I was wondering if you have other models available, or an idea to help me work around this issue. 

Thanks and have a nice day!

**Comment by robertanto** [comment]
Have you updated the parameters in the [params.py](https://github.com/robertanto/Real-Time-Sound-Event-Detection/blob/main/keras_yamnet/params.py 
) file?


The network adopts a Global Average Pooling layer after the convolutional part invariant to the input size. 
By modifying the param file accordingly you will be able to manage smaller windows.
