### ISSUE TITLE
i use it in the 8000hz  wav audio chunk ,it will return ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 96, 64), found shape=(None, 198, 64)

### ISSUE THREAD

**Issue by herbiel** [robertanto/Real-Time-Sound-Event-Detection#4]
i use it in the 8000hz  wav audio chunk ,it will return ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 96, 64), found shape=(None, 198, 64)

**Comment by robertanto** [comment]
Hi! 

May you share more details about your issue?

Did you just passed a 8KHz audio input? Or, instead, you changed the model parameters?

In the second case, even if you change the input shape of the model it may (quite sure) perform worse than the one deployed with the same setup of the training.

**Comment by robertanto** [comment]
Closed due to inactivity.

**Comment by herbiel** [comment]
how to change the model parameter?

**Comment by robertanto** [comment]
In the params.py file.
